### ISSUE TITLE
Опечатка в коде

### ISSUE THREAD

**Issue by sxquer** [meowto16/profitbase#1]
vendor/meowto16/profitbase/src/Base.php:63
        
            $tokenDataDecoded = $response;

            $tokenDataDecoded["time_of_receive"] = date(U); - **нужны кавычки вокруг U**

            $tokenDataEncoded = json_encode($tokenDataDecoded);

            $tokenDataResource = fopen($authorizeDataFile, "w");

            fwrite($tokenDataResource, $tokenDataEncoded);

            fclose($tokenDataResource);

**Comment by meowto16** [comment]
https://github.com/meowto16/profitbase/commit/9b6f1769d07b1440e180486021cf577ba4c5a377
